### ISSUE TITLE
Answer refutation

### ISSUE THREAD

**Issue by LifeIsStrange** [ml-jku/hopular#1]
@bschaefl Hi, hopfield networks are very interesting and understudied indeed however, can you please answer this?
https://medium.com/@tunguz/trouble-with-hopular-6649f22fa2d3

**Comment by Isinlor** [comment]
They provided answer here: https://twitter.com/bschaefl/status/1532739442930245635

**Comment by bschaefl** [comment]
Hi @LifeIsStrange,

yes, we already published an answer. Thanks @Isinlor for providing the corresponding link.

Closing this issue.
